
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import os

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def record_window():

    def clear_txt():
        phone_txbox.delete(0, END)  
        customername_txbox.delete(0, END)
        postal_txbox.delete(0, END)
        address1_txbox.delete(0, END)
        address2_txbox.delete(0, END)
        address3_txbox.delete(0, END)
        incharge_txbox.delete(0, END)
        doubleaddress_txbox.delete(0, END)

    def submit():
        pass



    leaf = Toplevel()
    leaf.title("record")
    leaf_canvas = Canvas(leaf, width=800,height=600, background="Black")
    leaf_canvas.grid(column=0,row=0)

    bg = PhotoImage(file = "./record/assets/image_1.png")
    leaf_canvas_bg = leaf_canvas.create_image(
        720,
        512,
        image = bg
    )

    leaf_canvas.create_text(
        56.0,
        26.0,
        anchor="nw",
        text="住所登録",
        fill="#FFFFFF",
        font=("Inter SemiBold", 36 * -1),
        
    )

    leaf_canvas.create_rectangle(
        51, #x
        92, #y
        697, #width
        93, # base on y. y+val = tickness of line
        fill="#FFFFFF",
        outline=""
    )

    leaf_canvas.create_text(
        56,
        117,
        anchor="nw",
        text="Phone Number",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        162,
        anchor="nw",
        text="Customer Name",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        204,
        anchor="nw",
        text="Postal Code",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        246,
        anchor="nw",
        text="Address 1",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        289,
        anchor="nw",
        text="Address 2",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        329,
        anchor="nw",
        text="Address 3",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        414,
        anchor="nw",
        text="Double Address",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )

    leaf_canvas.create_text(
        56,
        456,
        anchor="nw",
        text="In Charge",
        fill="#FFFFFF",
        font=("Inter", 24 * -1)
    )


    phone_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    phone_txbox.place(
        x=296,
        y=112,
        width=396,
        height=31
    )

    customername_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    customername_txbox.place(
        x=296,
        y=154,
        width=396,
        height=31
    )

    postal_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    postal_txbox.place(
        x=296,
        y=196,
        width=102,
        height=31
    )

    address1_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    address1_txbox.place(
        x=296,
        y=238,
        width=396,
        height=31
    )

    address2_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    address2_txbox.place(
        x=296,
        y=280,
        width=396,
        height=31
    )

    address3_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    address3_txbox.place(
        x=296,
        y=322,
        width=396,
        height=31
    )

    doubleaddress_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    doubleaddress_txbox.place(
        x=296,
        y=406,
        width=396,
        height=31
    )

    incharge_txbox = Entry(
        leaf_canvas,
        bd=0,
        bg="#FFF3FB",
        fg="#000716",
        font='Inter 16 bold',
        highlightthickness=0
    )

    incharge_txbox.place(
        x=296,
        y=448,
        width=396,
        height=31
    )

    submit_btn_image = PhotoImage(file="./record/assets/btn.png")
    submit_btn = Button(
        leaf_canvas,
        image=submit_btn_image,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("submit"),
        relief="flat"
    )
    
    submit_btn.place(
        x=410,
        y=523,
        width=125,
        height=34
    )

    clear_btn_image = PhotoImage(file="./record/assets/clear.png")
    clear_btn = Button(
        leaf_canvas,
        image=clear_btn_image,
        borderwidth=0,
        highlightthickness=0,
        command=clear_txt,
        relief="flat"
    )
    
    clear_btn.place(
        x=265,
        y=523,
        width=125,
        height=34
    )


    leaf.resizable(False,False)
    leaf.mainloop()



window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_1
)
canvas.create_text(
    178.0,
    68.0,
    anchor="nw",
    text="楽商 JVer",
    fill="#FFFFFF",
    font=("Inter SemiBold", 96 * -1)
)

canvas.create_rectangle(
    100.0,
    203.0,
    1338.0,
    205.0,
    fill="#FFFFFF",
    outline="")

#107 Torikeshi
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: window.destroy(),
    relief="flat"
)
button_1.place(
    x=728.0,
    y=608.0,
    width=618.0,
    height=78.0
)


#106 Nyuushukko
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=728.0,
    y=487.0,
    width=618.0,
    height=78.0
)

#105 Tanaoroshi
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=728.0,
    y=367.0,
    width=618.0,
    height=78.0
)

#104 Chuumon Rireki
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=728.0,
    y=247.0,
    width=618.0,
    height=78.0
)


#103 Uriage Shoukai
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=102.0,
    y=607.0,
    width=618.0,
    height=78.0
)


#102 Chuumon
button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=102.0,
    y=487.0,
    width=618.0,
    height=78.0
)


#101 Shouhin Touroku
button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7"),
    relief="flat"
)
button_7.place(
    x=102.0,
    y=367.0,
    width=618.0,
    height=78.0
)


#100 Jusho Touroku
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=record_window,
    relief="flat"
)
button_8.place(
    x=102.0,
    y=247.0,
    width=618.0,
    height=78.0
)


window.resizable(False, False)
window.mainloop()
